### ISSUE TITLE
你好，请问一下有详细的部署文档吗，我只会部署javaweb项目，你这个node ts的不太会部署呢

### ISSUE THREAD

**Issue by listky** [zrk1993/autojs-web-control#1]
你好，请问一下有详细的部署文档吗，我只会部署javaweb项目，你这个node ts的不太会部署呢

**Comment by listky** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:281:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:115:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
5 verbose cwd C:\Users\Tank\Desktop\autojs-web-control-master\server
6 verbose Windows_NT 10.0.18363
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
8 verbose node v12.14.1
9 verbose npm  v6.13.4
10 error missing script: start
11 verbose exit [ 1, true ]

我照着readme描述用的npm install ;npm run start两条命令，保证所有的node环境都装上了，然后报了如上的错误，是不是package.json配置没有提交呢，我不太清楚start应该配置哪一个作为入口启动文件，麻烦提示一下，谢谢了

**Comment by ztxwd** [comment]
我写了个简单的搭建教程，供大家参考
http://91fans.com.cn/post/autojswebone/

**Comment by zkbqhuang** [comment]
> 我写了个简单的搭建教程，供大家参考
> http://91fans.com.cn/post/autojswebone/
@ztxwd
请问 sayHelloToServer()中的RcDate和getCount()是不是缺少的？能补充一下吗？谢谢！
